import type { Metadata } from "next";
import "./globals.css";
import { Lexend, Cinzel, Space_Mono, Cormorant, Space_Grotesk } from 'next/font/google'
import Header from "./home-page-components/header";
import AnimationWrapper from "./home-page-components/animation_wrapper";
import { AnimatePresence } from "motion/react";

export const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
})

export const cinzel = Cinzel({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cinzel',
})

export const spaceMono = Space_Mono({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-mono',
})

export const cormorant = Cormorant({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-cormorant',
})

export const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-grotesk',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} ${cinzel.variable} ${spaceMono.variable} ${cormorant.variable} ${spaceGrotesk.variable} font-lexend bg-home_page-bg-medium text-black`}
      >
        <div>
          <Header/>
          <AnimatePresence mode="wait">
          {children}
          </AnimatePresence>
        </div>
      </body>
    </html>
  );
}
